Version embedding for Go 1.4 and 1.5
Go 1.5 linker has a slightly different -X flag format
so the build script has to support both variants.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,9 +1,24 @@
 #!/bin/bash -e
 
+function linker_dashX {
+	local version=$(go version)
+	local regex="go([0-9]+).([0-9]+)."
+	if [[ $version =~ $regex ]]; then
+		if [ ${BASH_REMATCH[1]} -eq "1" -a ${BASH_REMATCH[2]} -le "4" ]; then
+			echo "$1 \"$2\""
+		else
+			echo "$1=$2"
+		fi
+	else
+		echo "could not determine Go version"
+		exit 1
+	fi
+}
+
 ORG_PATH="github.com/coreos"
 REPO_PATH="${ORG_PATH}/flannel"
 VERSION=$(git describe --dirty)
-GLDFLAGS="-X github.com/coreos/flannel/version.Version \"${VERSION}\""
+GLDFLAGS="-X $(linker_dashX github.com/coreos/flannel/version.Version ${VERSION})"
 
 if [ ! -h gopath/src/${REPO_PATH} ]; then
 	mkdir -p gopath/src/${ORG_PATH}
