test: add license header check + missing headers

diff --git a/test b/test
--- a/test
+++ b/test
@@ -47,4 +47,13 @@ if [ -n "${fmtRes}" ]; then
 	exit 255
 fi
 
+echo "Checking for license header..."
+licRes=$(for file in $(find . -type f -iname '*.go' ! -path './Godeps/*'); do
+		head -n3 "${file}" | grep -Eq "(Copyright|generated|GENERATED)" || echo -e "  ${file}"
+	done;)
+if [ -n "${licRes}" ]; then
+	echo -e "license header checking failed:\n${licRes}"
+	exit 255
+fi
+
 echo "Success"
