glide: add k8s deps

diff --git a/vendor/github.com/coreos/etcd/test b/vendor/github.com/coreos/etcd/test
--- a/vendor/github.com/coreos/etcd/test
+++ b/vendor/github.com/coreos/etcd/test
@@ -13,14 +13,22 @@ set -e
 # Invoke ./cover for HTML output
 COVER=${COVER:-"-cover"}
 
+GO_BUILD_FLAGS=-a
 source ./build
 
+# Set up gopath so tests use vendored dependencies
+export GOPATH=${PWD}/gopath
+rm -f $GOPATH/src
+mkdir -p $GOPATH
+ln -s ${PWD}/cmd/vendor $GOPATH/src
+
 # Hack: gofmt ./ will recursively check the .git directory. So use *.go for gofmt.
-TESTABLE_AND_FORMATTABLE="client discovery error etcdctl/command etcdmain etcdserver etcdserver/auth etcdserver/etcdhttp etcdserver/etcdhttp/httptypes pkg/fileutil pkg/flags pkg/idutil pkg/ioutil pkg/netutil pkg/osutil pkg/pbutil pkg/types pkg/transport pkg/wait proxy raft snap store version wal"
+PKGS=`ls pkg/*/*go  | cut -f1,2 -d/ | sort | uniq`
+TESTABLE_AND_FORMATTABLE="client clientv3 discovery error etcdctl/ctlv2 etcdctl/ctlv3 etcdmain etcdserver etcdserver/auth etcdserver/api/v2http etcdserver/api/v2http/httptypes $PKGS proxy raft snap storage storage/backend store version wal"
 # TODO: add it to race testing when the issue is resolved
 # https://github.com/golang/go/issues/9946
 NO_RACE_TESTABLE="rafthttp"
-FORMATTABLE="$TESTABLE_AND_FORMATTABLE $NO_RACE_TESTABLE *.go etcdctl/ integration"
+FORMATTABLE="$TESTABLE_AND_FORMATTABLE $NO_RACE_TESTABLE *.go etcdctl/ integration clientv3/integration e2e alarm"
 
 # user has not provided PKG override
 if [ -z "$PKG" ]; then
@@ -44,43 +52,90 @@ split=(${TEST// / })
 TEST=${split[@]/#/${REPO_PATH}/}
 split=(${NO_RACE_TEST// / })
 NO_RACE_TEST=${split[@]/#/${REPO_PATH}/}
-
-echo "Running tests..."
-
 MACHINE_TYPE=$(uname -m)
 if [ $MACHINE_TYPE != "armv7l" ]; then
-  RACE="--race"
+	RACE="--race"
 fi
 
-go test -timeout 3m ${COVER} $@ ${TEST} ${RACE} -cpu 1,2,4
-go test -timeout 3m ${COVER} $@ ${NO_RACE_TEST} -cpu 1,2,4
+function unit_tests {
+	echo "Running tests..."
+	go test -timeout 3m ${COVER} ${RACE} -cpu 1,2,4 $@ ${TEST}
+	go test -timeout 3m ${COVER} -cpu 1,2,4 $@ ${NO_RACE_TEST}
+}
 
-if [ -n "$INTEGRATION" ]; then
+function integration_tests {
 	echo "Running integration tests..."
-	go test -timeout 10m $@ ${REPO_PATH}/integration -v -cpu 1,2,4
-fi
+	go test -timeout 10m -v -cpu 1,2,4 $@ ${REPO_PATH}/e2e
+	go test -timeout 15m -v -cpu 1,2,4 $@ ${REPO_PATH}/integration
+	go test -timeout 10m -v ${RACE} -cpu 1,2,4 $@ ${REPO_PATH}/clientv3/integration
+	go test -timeout 1m -v -cpu 1,2,4 $@ ${REPO_PATH}/contrib/raftexample
+}
 
-echo "Checking gofmt..."
-fmtRes=$(gofmt -l $FMT)
-if [ -n "${fmtRes}" ]; then
-	echo -e "gofmt checking failed:\n${fmtRes}"
-	exit 255
-fi
+function fmt_tests {
+	echo "Checking gofmt..."
+	fmtRes=$(gofmt -l -s -d $FMT)
+	if [ -n "${fmtRes}" ]; then
+		echo -e "gofmt checking failed:\n${fmtRes}"
+		exit 255
+	fi
 
-echo "Checking govet..."
-vetRes=$(go vet $TEST)
-if [ -n "${vetRes}" ]; then
-	echo -e "govet checking failed:\n${vetRes}"
-	exit 255
-fi
+	echo "Checking govet..."
+	vetRes=$(go vet $TEST)
+	if [ -n "${vetRes}" ]; then
+		echo -e "govet checking failed:\n${vetRes}"
+		exit 255
+	fi
 
-if command -v go-nyet >/dev/null 2>&1; then
-  echo "Checking go-nyet..."
-  nyetRes=$(go-nyet -exitWith 0 $FMT)
-  if [ -n "${nyetRes}" ]; then
-          echo -e "go-nyet checking failed:\n${nyetRes}"
-          exit 255
-  fi
-fi
+	echo "Checking govet -shadow..."
+	for path in $FMT; do
+		vetRes=$(go tool vet -shadow ${path})
+		if [ -n "${vetRes}" ]; then
+			echo -e "govet checking ${path} failed:\n${vetRes}"
+			exit 255
+		fi
+	done
 
+	echo "Checking goword..."
+	# get all go files to process
+	gofiles=`find $FMT -iname '*.go' 2>/dev/null`
+	# ignore tests and protobuf files
+	gofiles=`echo ${gofiles} | sort | uniq | sed "s/ /\n/g" | egrep -v "(\\_test.go|\\.pb\\.go)"`
+	# only check for broken exported godocs
+	gowordRes=`goword -use-spell=false ${gofiles} | grep godoc-export | sort`
+	if [ ! -z "$gowordRes" ]; then
+		echo -e "goword checking failed:\n${gowordRes}"
+		exit 255
+	fi
+
+	echo "Checking for license header..."
+	licRes=$(for file in $(find . -type f -iname '*.go' ! -path './cmd/*'); do
+			head -n3 "${file}" | grep -Eq "(Copyright|generated|GENERATED)" || echo -e "  ${file}"
+		done;)
+	if [ -n "${licRes}" ]; then
+		echo -e "license header checking failed:\n${licRes}"
+		exit 255
+	fi
+}
+
+function dep_tests {
+	echo "Checking package dependencies..."
+	# don't pull in etcdserver package
+	pushd clientv3 >/dev/null
+	badpkg="(etcdserver|storage)"
+	deps=`go list -f '{{ .Deps }}'  | sed 's/ /\n/g' | egrep "${badpkg}" | egrep -v "${badpkg}/" || echo ""`
+	popd >/dev/null
+	if [ ! -z "$deps" ]; then
+		echo -e "clientv3 has masked dependencies:\n${deps}"
+		exit 255
+	fi
+}
+
+# fail fast on static tests
+fmt_tests
+dep_tests
+
+unit_tests
+if [ -n "$INTEGRATION" ]; then
+	integration_tests
+fi
 echo "Success"
